project:
  type: book
  output-dir: docs

book:
  title: "Hyggematematik"
  author: "Selma og Lasse"
  date: "today"
  language: "da"
  chapters:
    - index.qmd
    - differentialregning.qmd
    - enheder.qmd
    - potenser-rodder.qmd

format:
  html:
    theme: cosmo
    number-sections: false 
    toc-title: "Indhold"

execute: 
    echo: false
    warning: false
    message: false
    
lang: "da"