project:
  type: book
  output-dir: docs
book:
  title: "Hyggematematik"
  author: "Selma og Lasse"
  date: "today"
  language: "da"
  chapters:
    - index.qmd
    - enheder.qmd
    - potenser-rodder.qmd
    - differentialregning.qmd
format:
  html:
    theme: cosmo
    number-sections: false
    toc-title: "Indhold"
    pandoc-args: ["--filter", "pandoc-crossref"]
crossref:
  chapters: true
  title-delim: ": "
execute:
  echo: false
  warning: false
  message: false
lang: "da"